# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
version: 2.1
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            -  build
      - analyze:
          requires:
            - test
